#### Numpy Array Creation

In [2]:
import numpy as np

In [ ]:
### Create a array
np.linspace(0,1,5)  ### 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.normal(1,2,(2,3))

array([[ 4.70082421,  1.59890418, -2.21627095],
       [ 2.99345431,  2.23308932,  1.66333781]])

In [25]:
## Random Creation
x1=np.random.randint(5,10,(1))  ## one dimentional array
x2=np.random.randint(5,10,(1,3))
x3 = np.random.randint(5,10,(3,4,5))
print(x1)
print(x2)
print("Three dimension array \n",x3)

[7]
[[5 7 8]]
Three dimension array 
 [[[5 6 6 8 5]
  [5 9 8 5 5]
  [8 6 9 8 8]
  [5 7 9 8 9]]

 [[6 9 6 6 9]
  [9 7 7 7 5]
  [8 9 5 5 7]
  [5 5 7 8 7]]

 [[7 6 7 7 7]
  [5 7 9 6 8]
  [8 7 7 5 9]
  [7 9 5 6 8]]]


In [26]:
print(x3.ndim)
print(x3.shape)
print(x3.size)

3
(3, 4, 5)
60
